<?php
/**
 * Template Name: STARK Company Page
 * Template Post Type: page
 *
 * @package BlueMattress
 */

get_header();
$facts = blue_field( 'stark_facts', array(
	array( 'value' => '+45', 'label' => blue_text( 'Years of experience', 'سنة من الخبرة' ) ),
	array( 'value' => '60,000 m²', 'label' => blue_text( 'Facilities in Jeddah', 'منشآت في جدة' ) ),
	array( 'value' => '+200', 'label' => blue_text( 'Specialists', 'متخصص' ) ),
	array( 'value' => '3/yr', 'label' => blue_text( 'Mega-projects delivered', 'مشاريع كبرى سنويًا' ) ),
) );
$milestones = blue_field( 'stark_milestones', array(
	array( 'label' => '1967', 'description' => blue_text( 'The beginning of decades of Saudi industrial experience in foam manufacturing.', 'بداية عقود من الخبرة الصناعية السعودية في تصنيع الإسفنج.' ) ),
	array( 'label' => blue_text( 'Growth', 'النمو' ), 'description' => blue_text( 'The company expanded into mattresses, furniture and the wood industry.', 'توسعت الشركة في صناعة المراتب والأثاث والصناعات الخشبية.' ) ),
	array( 'label' => 'STARK', 'description' => blue_text( 'One identity uniting knowledge, manufacturing scale and inherited craftsmanship.', 'هوية واحدة تجمع المعرفة وحجم التصنيع والحرفية المتوارثة.' ) ),
) );
$factory_image = blue_image_url( blue_field( 'stark_factory_image' ), BLUE_THEME_URI . '/assets/img/stark-factory.jpg' );
$craft_image = blue_image_url( blue_field( 'stark_craft_image' ), BLUE_THEME_URI . '/assets/img/stark-craft.jpg' );
$wood_image = blue_image_url( blue_field( 'stark_wood_image' ), BLUE_THEME_URI . '/assets/img/stark-wood.jpg' );
$bed_image = blue_image_url( blue_field( 'stark_bed_image' ), BLUE_THEME_URI . '/assets/img/stark-bed.jpg' );
?>
<main id="primary" class="stark-page">
	<section class="sk-hero"><div class="container"><p class="eyebrow"><?php echo esc_html( blue_text( 'The mother company', 'الشركة الأم' ) ); ?></p><h1 class="display sk-name">STARK</h1><p class="sk-tag display"><?php echo esc_html( blue_field( 'stark_tagline', blue_text( 'Built on Trust. Guided by Knowledge.', 'بُنيت على الثقة. تقودها المعرفة.' ) ) ); ?></p><p class="sk-expand"><?php echo esc_html( blue_field( 'stark_expansion', blue_text( 'Strategic Trust for Advanced & Reliable Knowledge', 'الثقة الاستراتيجية للمعرفة المتقدمة والموثوقة' ) ) ); ?></p></div></section>
	<section class="sk-facts"><div class="container"><div class="sk-facts-card"><?php foreach ( is_array( $facts ) ? $facts : array() as $fact ) : ?><div class="sk-fact"><b><?php echo esc_html( $fact['value'] ?? '' ); ?></b><span><?php echo esc_html( $fact['label'] ?? '' ); ?></span></div><?php endforeach; ?></div></div></section>
	<section class="section-tight"><div class="container sk-overview"><div><div class="sec-head"><p class="eyebrow"><?php echo esc_html( blue_text( 'Company overview', 'نبذة عن الشركة' ) ); ?></p><h2 class="display h2"><?php echo esc_html( blue_field( 'stark_overview_heading', blue_text( 'The invisible foundation of every great space.', 'الأساس الخفي لكل مساحة عظيمة.' ) ) ); ?></h2></div><div class="lead stark-rich"><?php echo wp_kses_post( blue_field( 'stark_overview_body', blue_text( '<p>STARK provides integrated manufacturing solutions specialising in woodwork, furniture and mattress manufacturing. From its Jeddah facility, the group combines advanced machinery with deep craftsmanship to deliver at scale.</p>', '<p>تقدم ستارك حلول تصنيع متكاملة متخصصة في الأعمال الخشبية والأثاث وصناعة المراتب. ومن منشأتها في جدة تجمع المجموعة بين الآلات المتقدمة والحرفية العميقة للإنتاج على نطاق واسع.</p>' ) ) ); ?></div><div class="sk-sectors"><span><?php echo esc_html( blue_text( 'Residential', 'سكني' ) ); ?></span><span><?php echo esc_html( blue_text( 'Commercial', 'تجاري' ) ); ?></span><span><?php echo esc_html( blue_text( 'Hospitality', 'ضيافة' ) ); ?></span><span><?php echo esc_html( blue_text( 'Healthcare', 'رعاية صحية' ) ); ?></span><span><?php echo esc_html( blue_text( 'Government', 'حكومي' ) ); ?></span></div></div><figure class="sk-photo"><img src="<?php echo esc_url( $factory_image ); ?>" alt="<?php echo esc_attr( blue_text( 'STARK manufacturing facility', 'منشأة ستارك للتصنيع' ) ); ?>" loading="lazy"></figure></div></section>
	<section class="sk-heritage section-tight"><div class="container"><div class="sec-head"><p class="eyebrow"><?php echo esc_html( blue_text( 'Since 1967', 'منذ 1967' ) ); ?></p><h2 class="display h2"><?php echo esc_html( blue_field( 'stark_heritage_heading', blue_text( 'Built on experience and trust.', 'بُنيت على الخبرة والثقة.' ) ) ); ?></h2></div><div class="sk-mile-grid"><?php foreach ( is_array( $milestones ) ? $milestones : array() as $milestone ) : ?><div class="sk-mile"><b><?php echo esc_html( $milestone['label'] ?? '' ); ?></b><p><?php echo esc_html( $milestone['description'] ?? '' ); ?></p></div><?php endforeach; ?></div></div></section>
	<section class="section-tight"><div class="container"><div class="sk-grid"><article class="sk-card"><h3><?php echo esc_html( blue_text( 'Vision', 'الرؤية' ) ); ?></h3><p><?php echo esc_html( blue_field( 'stark_vision', blue_text( 'To lead in integrated industrial solutions that strengthen national industry and improve quality of life.', 'الريادة في الحلول الصناعية المتكاملة التي تعزز الصناعة الوطنية وتحسن جودة الحياة.' ) ) ); ?></p></article><article class="sk-card"><h3><?php echo esc_html( blue_text( 'Mission', 'الرسالة' ) ); ?></h3><p><?php echo esc_html( blue_field( 'stark_mission', blue_text( 'To deliver reliable products and services through expertise, specialised talent and exacting quality standards.', 'تقديم منتجات وخدمات موثوقة بالخبرة والكفاءات المتخصصة وأعلى معايير الجودة.' ) ) ); ?></p></article></div></div></section>
	<figure class="sk-band"><img src="<?php echo esc_url( $craft_image ); ?>" alt="" loading="lazy"><figcaption><?php echo esc_html( blue_field( 'stark_craft_caption', blue_text( 'Craftsmanship on the factory floor — where wood and sleep meet.', 'حرفية على أرض المصنع — حيث يلتقي الخشب بالنوم.' ) ) ); ?></figcaption></figure>
	<section class="section-tight"><div class="container"><div class="sec-head"><p class="eyebrow"><?php echo esc_html( blue_text( 'What STARK makes', 'ما تصنعه ستارك' ) ); ?></p><h2 class="display h2"><?php echo esc_html( blue_text( 'Two divisions, one standard.', 'قطاعان، معيار واحد.' ) ); ?></h2></div><div class="sk-grid"><article class="sk-card sk-card-photo"><img src="<?php echo esc_url( $wood_image ); ?>" alt="" loading="lazy"><h3><?php echo esc_html( blue_text( 'Wood Manufacturing & Joinery', 'تصنيع الأخشاب والنجارة' ) ); ?></h3><p><?php echo esc_html( blue_field( 'stark_wood_text', blue_text( 'Custom woodwork, furniture, joinery and fit-outs from design through installation.', 'أعمال خشبية وأثاث ونجارة وتجهيزات مخصصة من التصميم حتى التركيب.' ) ) ); ?></p></article><article class="sk-card sk-card-photo"><img src="<?php echo esc_url( $bed_image ); ?>" alt="" loading="lazy"><h3><?php echo esc_html( blue_text( 'Mattress Solutions', 'حلول المراتب' ) ); ?></h3><p><?php echo esc_html( blue_field( 'stark_bed_text', blue_text( 'Complete sleep solutions for homes, hospitality, healthcare and commercial spaces.', 'حلول نوم متكاملة للمنازل والضيافة والرعاية الصحية والمساحات التجارية.' ) ) ); ?></p></article></div></div></section>
	<section class="sk-contact section-tight"><div class="container"><div class="sec-head center"><p class="eyebrow">STARK</p><h2 class="display h2"><?php echo esc_html( blue_text( 'Get in touch with the group.', 'تواصل مع المجموعة.' ) ); ?></h2></div><div class="sk-contact-line"><a href="mailto:<?php echo esc_attr( blue_field( 'stark_email', 'Info@Stark.com.sa' ) ); ?>" dir="ltr"><?php echo esc_html( blue_field( 'stark_email', 'Info@Stark.com.sa' ) ); ?></a><a href="<?php echo esc_url( blue_field( 'stark_website', 'https://stark.com.sa' ) ); ?>" target="_blank" rel="noopener" dir="ltr">Stark.com.sa</a><span><?php echo esc_html( blue_field( 'stark_address', blue_text( '3rd Industrial Area, Jeddah', 'المدينة الصناعية الثالثة، جدة' ) ) ); ?></span></div><div class="sk-back"><a class="btn" href="<?php echo esc_url( blue_home_url( '/' ) ); ?>"><?php echo esc_html( blue_text( 'Back to Blue Mattresses', 'العودة إلى مراتب بلو' ) ); ?></a></div></div></section>
</main>
<?php get_footer(); ?>
